### ISSUE TITLE
错误信息：Db driver '' not exist，手动配置数据库配置后，并需要手动新建一个数据库，这个问题才能解决

### ISSUE THREAD

**Issue by gouguoyin** [gouguoyin/phprap#1]
如果您在使用过程中有任何疑问，或有好的意见和想法，请在这里给我留言，我会及时回复。

**Comment by yuan-dian** [comment]
安装报错：
1、错误信息：Db driver '' not exist，手动配置数据库配置后，并需要手动新建一个数据库，这个问题才能解决
2、数据库密码不能为空
3、错误信息：Call to a member function fetchAll() on null，创建管理员出现这个错误

**Comment by gouguoyin** [comment]
感谢你的反馈，正在修复

**Comment by yuan-dian** [comment]
添加项目出现：SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'id' at row 1

**Comment by gouguoyin** [comment]
@yuan-dian 你下载的哪个分支版本？能把你的服务器环境发我下吗？

**Comment by yuan-dian** [comment]
https://gitee.com/gouguoyin/phprap.git；Git上面下载的，服务器环境windows+ apache+ php+ mysql5.7.14，还有一个问题，在PHP7.1版本安装执行SQL文件的时候出现错误：Too few arguments to function db(), 0 passed in ###\application\install\controller\step4.php on line 35 and exactly 2 expected，7.0、5.6没有问题

**Comment by yuan-dian** [comment]
还有一个建议，就是安装步骤，可以考虑一下，可以自动创建表和配置，你的现在必须先创建表，把db的配置文件配置正确才可以按装

**Comment by gouguoyin** [comment]
@yuan-dian 创建表的前提条件是连接数据库，安装程序这个时候还没有数据库信息，如何连接？如何创建表？

**Comment by yuan-dian** [comment]
你的第二步不是让用户输入数据库信息了吗，可以拿这些数据去连接数据库

**Comment by gouguoyin** [comment]
@yuan-dian 你的意思是把数据库配置信息存到数据库里？

**Comment by yuan-dian** [comment]
Nginx环境路由有问题，任何url，都跳转到home/index/index这个控制器里面

**Comment by torans** [comment]
NGINX+PHP5.6/7.0 直接500错误，‘拒绝了我们的连接请求’。

**Comment by lianjie5664** [comment]
在nginx上部署后，进入安装页面，跳转到install/step1.html 报500错误。

**Comment by gouguoyin** [comment]
@lianjie5664 检查项目目录是否由可写权限

**Comment by kakarotto1** [comment]
请求参数和响应参数不能区分 header 和 body 吗

**Comment by gouguoyin** [comment]
@kakarotto1 暂时不能，下个版本会优化

**Comment by gouguoyin** [comment]
@kakarotto1 1.0.4版本已支持header和body，并支持在线调试接口。

**Comment by gouguoyin** [comment]
该问题已彻底解决，请现在最新stable版本重新安装部署
