### ISSUE TITLE
v1.0.4，Too few arguments to function db()

### ISSUE THREAD

**Issue by crystalsis** [gouguoyin/phprap#37]
php7.1.11
安装1.0.4的时候提示
Too few arguments to function db(), 1 passed in phprap\application\install\controller\step4.php on line 59 and exactly 2 expected
gophp\function\function.php 错误行数:180

**Comment by juvevood** [comment]
同样的错误

**Comment by gouguoyin** [comment]
@juvevood 你也是7.1版本？

**Comment by gouguoyin** [comment]
@crystalsis  将gophp\function\function.php里的`db($table, $driver)`改为`db($table, $driver=null)`试试

**Comment by crystalsis** [comment]
改了之后是\gophp\library\db.php的59行报错 public function table($table, $prefix)这个
也是参数数量对不上，然后我额外装了个php5.6把这个站单独指定了一个php，然后新的问题就是这个站变得特别慢，还在继续折腾中

**Comment by juvevood** [comment]
@gouguoyin  是PHP7.1   改了还是报错

**Comment by gouguoyin** [comment]
@juvevood  我刚做了下修改，你从stable分支clone下来最新源码重新安装下

**Comment by juvevood** [comment]
@gouguoyin 现在这里报错 
错误信息：Too few arguments to function gophp\exception::__construct(), 2 passed in /home/www/phprap/gophp/library/db/driver/mysql.php on line 856 and exactly 3 expected

**Comment by gouguoyin** [comment]
@juvevood gophp/library/exception.php里的public function __construct($message, $sql, $code)改为public function __construct($message, $sql, $code = '')试下

**Comment by juvevood** [comment]
@gouguoyin 不行依然报错

**Comment by gouguoyin** [comment]
@juvevood 报什么错？

**Comment by gouguoyin** [comment]
该问题已彻底解决，请下载最新stable版本重新安装
