### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by wybwsk** [gouguoyin/phprap#52]
1、二级域名配置后，install会无限循环跳转step1。（服务器环境，rap.domain.com.cn，linux+nginx+php7）。
本地安装完后，把配置复制到相关环境下，同样无限循环跳转login，无法使用，无法访问，空。
nginx  
  default.conf
       server{
                listen 80;
                server_name  rap.domain.com.cn;
                root /var/www/rap/public;
                ......
        }

2、本地环境（windows+apache+php7）
Use of undefined constant DS - assumed 'DS' in E:\UPUPW_AP7.0_64\htdocs\phprap\public\index.php on line 7
修改“DS”为"/"就可以了。
每次让改密码很不爽。

**Comment by gouguoyin** [comment]
@wybwsk 请问你是下载的哪个版本？Use of undefined constant DS - assumed 'DS' in E:\UPUPW_AP7.0_64\htdocs\phprap\public\index.php on line 7这个BUG很早就修复了。只有你的密码和管理后台设置的默认密码一样时才会不断提示修改密码，后台默认密码是123456。这样做的目的是为了提示用户修改重置后的默认密码。

**Comment by wybwsk** [comment]
内部常用密码就是123456.。。。：）这个是个很多余的考虑，建议选择权放给用户。：）
另外，在TP上找到的。是1.05。

**Comment by gouguoyin** [comment]
@wybwsk 这个设计不多余，目的就是为了防止会员都采用一样的默认密码，如果不加以引导，最终大家的密码都一样，只要知道别人的邮箱地址，就能登录系统。源码建议在官网下载，官网地址[www.phprap.com](http://www.phprap.com/)
