### ISSUE TITLE
创建新项目貌似有bug

### ISSUE THREAD

**Issue by leirenzhichui** [gouguoyin/phprap#54]
project add() 的时候传了一个空id导致数据库报错，还是stable的分支

**Comment by gouguoyin** [comment]
@leirenzhichui 空id是怎么产生的？

**Comment by leirenzhichui** [comment]
@gouguoyin 好像是post参数传进来就有了

**Comment by gouguoyin** [comment]
@leirenzhichui 能把完整报错信息发下吗？

**Comment by leirenzhichui** [comment]
![image](https://user-images.githubusercontent.com/7393856/33421587-8291acc4-d5ed-11e7-852c-e13069637872.png)
@gouguoyin

**Comment by gouguoyin** [comment]
你这个是mysql版本造成的，具体解决方案看[http://www.phprap.com/doc/faq.html#faq1](http://www.phprap.com/doc/faq.html#faq1)

**Comment by leirenzhichui** [comment]
@gouguoyin 抱歉，怪我没看文档
