### ISSUE TITLE
develop 分支的安装脚本及sql文件 在哪 里？

### ISSUE THREAD

**Issue by westeast** [gouguoyin/phprap#93]

**Comment by gouguoyin** [comment]
runtime/install文件夹下，没有安装脚本，运行程序会自动进入安装程序

**Comment by westeast** [comment]
@gouguoyin   develop分支 现在也是这样的，但develop里没找到sql文件 呢？

**Comment by westeast** [comment]
@gouguoyin  我安装成功了develop多谢了，不过安装过程中sql语句有几个报错，都 是create_at update_at 时间 相关的，说是datetime default CURRENT_TIMESTAMP  报错？你用的mysql什么版本我这里是mysql5.5   ,我手动把sql语句修改成timestamp default CURRENT_TIMESTAMP 最后是安装成功了。
